language: java
dist: trusty
jdk:
- oraclejdk8
script:
- jdk_switcher use oraclejdk8
- cd Sanimal\ FX
- mvn -U compile package
deploy:
  provider: releases
  draft: true
  skip_cleanup: true
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: target/SanimalFX-1.0-SNAPSHOT-jar-with-dependencies.jar
  on:
    repo: CulverLab/sparcd
    tags: true
