language: java
dist: trusty
jdk:
  - oraclejdk8

script:
  - jdk_switcher use oraclejdk8
  - cd Sanimal\ FX
  - mvn -U compile package

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "target/SanimalFX-1.0-SNAPSHOT-jar-with-dependencies.jar"
  skip_cleanup: true
  draft: true
  on:
    tags: true
